### ISSUE TITLE
Data received three times in a row.

### ISSUE THREAD

**Issue by ernestum** [ggerganov/ggwave-arduino#3]
I am using the arduino-rx example with an Arduino RP2040 Connect with the default settings. I can send data flawlessly using the waver (and with a bit of tweeking/disabling DSS even with the python bindings) but the `ggwave.rxTakeData()` in line 291 reports each "packet" three times. Is this normal behavior? I fear that I somehow use the library wrong?

**Comment by ggerganov** [comment]
Yes, that's expected. The reason is that it is decoding the audio waveform via a running window and the payload can be decoded in multiple sequential windows (due to the ECC). You can either ignore received messages in short amount of time, or you can add an id to your payload so that the receiver can distinguish different message

**Comment by ernestum** [comment]
Ok that makes sense. Thanks for the hint I will do the id-solution.
